# Un tutorial de Numpy

El módulo NumPy (**Num**erical **Py**thon) es probablemente la paquetería de Python más utilizada en ciencias e ingeniería. Permite realizar operaciones matemáticas sobre arreglos sin necesidad de recurrir a bucles.

## ¿Por qué usar Numpy?
Hay varias razones para usar numpy:
* Operaciones vectorizadas
* Operaciones matemáticas y estadísticas
* Álgebra Lineal
* Números aleatorios



# Importando el módulo

In [1]:
import numpy as np

Lo anterior permite acceder a todas las funciones de `numpy` usando el alias `np`.

## ¿Qué es un arreglo?
Es una estructura utilizada para almacenar datos. En el caso de numpy, se almacenan datos numéricos.

**Arreglo de una dimensión**

Un arreglo unidimensional, puede representarse como una lista:

![Esquema de un arreglo](Figures/array-example.png)

### Crear un arreglo de una dimensión

In [2]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

**Arreglo de dos dimensiones**

Un arreglo bidimensional, puede representarse como una tabla o una matriz:

![Esquema de un arreglo de dos dimensiones](Figures/2d-array.png)

### Crear un arreglo de dos dimensiones

In [3]:
np.array([ [1, 2, 3, 4, 5, 6], 
          [7, 8, 9, 10, 11, 12], 
          [13, 14, 15, 16, 17, 18], 
          [19, 20, 21, 22, 23, 24] ])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

### Crear arreglos a partir de listas

In [31]:
#- Listas
lista_1 = [5, 1, 4,6]
type(lista_1)

list

In [32]:
#- Arreglos
arreglo = np.array(lista_1)
type(arreglo)

numpy.ndarray

In [33]:
arreglo

array([5, 1, 4, 6])

### Operaciones de un arreglo con un escalar

In [15]:
lista_1*3.5

TypeError: can't multiply sequence by non-int of type 'float'

In [16]:
arreglo*3.5

array([ 0. ,  3.5,  7. , 10.5])

### Los arreglos son iterables
Esto significa, que se puede acceder a sus elementos mediante índices

In [34]:
#- Accediendo a los elementos
arreglo

array([5, 1, 4, 6])

In [35]:
arreglo[1]

1

In [36]:
for num in arreglo:
    print(num)

5
1
4
6


In [43]:
for index in range(len(arreglo)):
    #- Muestra el valor del elemento
    print(arreglo[index])

    #- Elemento en la posición 3
    if index == 2:
        #- Reemplazar el elemento 
        arreglo[index] = 100

5
1
100
6


In [42]:
arreglo

array([  5,   1, 100,   6])

In [39]:
list(range(len(arreglo)))

[0, 1, 2, 3]

### Los arreglos se pueden rebanar (slicing)

**Para el caso unidimensional**

In [44]:
#- Definiendo el arreglo
nuevo_arreglo = np.array([6, 1, 45, 90, 34, 23])
nuevo_arreglo

array([ 6,  1, 45, 90, 34, 23])

In [45]:
#- Aplicando slices
sub_arreglo = nuevo_arreglo[1:-1]
sub_arreglo

array([ 1, 45, 90, 34])

In [55]:
nuevo_arreglo[::-2]

array([23, 90,  1])

In [57]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [58]:
data[0]

1

In [59]:
data[1]

2

In [62]:
data[-2:]

array([2, 3])

Para entender cómo funcionan los índices, analiza la siguiente figura

![Índices en un arreglo unidimensional](Figures/np_indexing.png)

**Para el caso bidimensional**

In [64]:
#- Definiendo la matriz
data = np.array([ [1, 2], [3, 4], [5, 6] ])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
#- Accediendo a los elementos mediante índices
data[0 , 1]

2

In [66]:
#- Aplicando slicing
data[1:3]

array([[3, 4],
       [5, 6]])

In [67]:
data[0:2, 0]

array([1, 3])

In [77]:
data[0][1]

2

In [80]:
data + 4

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [82]:
data - 6

array([[-5, -4],
       [-3, -2],
       [-1,  0]])

Para entenderlo mejor, puedes visualizarlo con la figura:

![Índices en un arreglo bidimensional](Figures/np_matrix_indexing.png)

## Atributos de un arreglo de NumPy
Algunos de los atributos de los arreglos son `ndim`, `shape`, `size` y `dtype`.

### El atributo ndim
Nos dice el número de dimensiones con las que cuenta el array

In [84]:
data.ndim

2

In [86]:
arreglo.ndim

1

### El atributo shape
Es una tupla de enteros positivos que nos indica la cantidad de elementos en cada dimensión del arreglo

In [88]:
data.shape

(3, 2)

In [89]:
arreglo.shape

(4,)

### El atributo size
Nos indica la cantidad total de elementos con los que cuenta un arreglo

In [90]:
data.size

6

In [91]:
arreglo.size

4

### El atributo dtype
Nos indica el tipo de datos del que está formado un arreglo

In [95]:
data.dtype

dtype('int32')

In [106]:
data2 = np.array([0, 1, 2, 4, 7.8], dtype=float)
data2

array([0. , 1. , 2. , 4. , 7.8])

## Operaciones útiles
Entre las operaciones más útiles de un arreglo está encontrar el mínimo, máximo, suma, promedio y desviación estándar

### Mínimo, máximo y suma de un arreglo

**Para el caso unidimensional**

In [138]:
arreglo_uni = np.array([7, 14, 2, 100])
arreglo_uni

array([  7,  14,   2, 100])

In [126]:
print(f'El mínimo del arreglo es {arreglo_uni.min()}')
print(f'El máximo del arreglo es {arreglo_uni.max()}')
print(f'La suma de los elementos del arreglo es {arreglo_uni.sum()}')
print(f'El promedio del arreglo es {arreglo_uni.mean()}')
print(f'La desviación estándar del arreglo es {arreglo_uni.std()}')

El mínimo del arreglo es 2
El máximo del arreglo es 100
La suma de los elementos del arreglo es 123
El promedio del arreglo es 30.75
La desviación estándar del arreglo es 40.20805267604985


In [119]:
np.std([1,3,4,5])

1.479019945774904

**Para el caso bidimensional**

In [120]:
data3 = np.array([ [1, 2], [5, 3], [4, 6] ])
data3

array([[1, 2],
       [5, 3],
       [4, 6]])

También es posible indicar la dirección sobre la cual operar

In [124]:
data3.max(axis=0)

array([5, 6])

In [125]:
data3.max(axis=1)

array([2, 5, 6])

Para comprenderlo de mejor manera, puedes visualizarlo con la siguiente figura:

![Axis en un arreglo bidimensional](Figures/np_matrix_aggregation_row.png)

### Promedio y desviación estándar de un arreglo

In [132]:
data3.std(axis=0)

array([1.69967317, 1.69967317])

In [133]:
data3.std(axis=1)

array([0.5, 1. , 1. ])

In [131]:
data3.sum(axis=1)

array([ 3,  8, 10])

## Juntando y ordenando arreglos

### El método sort()
Ordena de menor a mayor los elementos de un arreglo

In [140]:
arreglo_uni

array([  7,  14,   2, 100])

In [149]:
arreglo_uni.sort()
arreglo_uni

array([  2,   7,  14, 100])

In [150]:
arreglo_uni[::-1]

array([100,  14,   7,   2])

In [142]:
data3

array([[1, 2],
       [5, 3],
       [4, 6]])

In [147]:
data3.sort()
data3

array([[1, 2],
       [3, 5],
       [4, 6]])

### La operación concatenate()
Une dos o más arreglos. Para esto, los ingresamos como una tupla

In [151]:
a1 = np.array([1,2,3])
a2 = np.array([6,7,8])

In [157]:
a3 = np.concatenate((a1, a2))
a3

array([1, 2, 3, 6, 7, 8])

También es posible añadir el parámetro `axis` para especificar la dirección

## Creando arreglos básicos
Las formas elementales para crear arreglos es mediante las funciones `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace` y `np.logspace()`

### Arreglos de ceros y unos
**Caso unidimensional**

In [165]:
np.zeros(2)

array([0., 0.])

In [164]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

**Caso bidimensional**

In [166]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [167]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Arreglos ordenados
**Usando np.arange()**

Se crea un arreglo desde un punto de inicio, un punto de llegada y los pasos

In [173]:
np.arange(1, 9, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9])

**Usando np.linspace()**

Se crea un arreglo desde un punto de inicio, un punto de llegada, y la cantidad de elementos

In [175]:
np.linspace(1, 9, 10, endpoint=True)

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

**Usando np.logspace()**

Similar a `np.linspace()`, pero el arreglo se crea logarítmicamente espaciado

In [180]:
np.logspace(-1, 1, 3, base=np.e, endpoint=True)

array([0.36787944, 1.        , 2.71828183])

In [178]:
help(np.logspace)

Help on _ArrayFunctionDispatcher in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.

    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported

    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boo

## Creando arreglos aleatorios
El submódulo `np.random` contiene múltiples generadores de números aleatorios para crear arreglos. Puedes ver todas los generadores disponibles en este [enlace](https://numpy.org/doc/stable/reference/random/legacy.html). 

Acá solo veremos algunos de ellos.

### El generador de números aleatorios por defecto

In [188]:
rng = np.random.default_rng()
rng.random(3)

array([0.56552039, 0.78479891, 0.03306879])

### El generador np.random.rand()
Genera números aleatorios entre 0 y 1

In [190]:
np.random.rand(5)

array([0.70557116, 0.32724853, 0.11389192, 0.8804879 , 0.24034292])

### El generador np.random.randint()
Devuelve un arreglo de números enteros entre dos límites

In [194]:
np.random.randint(1, 9, 10)

array([4, 3, 1, 5, 4, 6, 2, 6, 2, 1])

### El generador np.random.normal()
Devuelve un arreglo de números aleatorios que siguen la distribución nomral:

$$
p(x) = \frac{1}{\sqrt{2\pi\sigma^2}}\exp\left[-\frac{(x-\mu)^2}{2\sigma^2}\right].
$$
Los parámetros de entrada son la media $\mu$ y la desviación estándar $\sigma$.

In [206]:
normal_dist = np.random.normal(100, 20, 50)
normal_dist

array([128.98752632,  90.90640806,  87.522744  ,  78.53166619,
       109.01215487, 104.29393224,  77.19786134,  98.23611053,
        96.07308706, 115.22133336,  84.73456393,  90.31428984,
       119.91782782,  87.57877683, 113.67138282,  85.99808354,
        82.02940026, 118.60492544,  99.91731119, 112.5337247 ,
       111.27357616, 114.52882488, 131.42825629,  82.33080601,
        97.6050884 ,  70.3180791 , 107.25234397,  77.8649253 ,
       147.60439593,  86.62862168, 115.89236714,  54.46927239,
        74.85011809, 107.04910322, 104.30400902,  82.71083935,
       107.04035081, 113.558103  , 120.60578198, 124.26901705,
        94.77979066, 112.23499743, 112.52599023, 140.09293831,
        68.57838545, 107.70700177,  93.96159423,  49.30856699,
        90.34222605, 111.63242872])

In [203]:
normal_dist.mean()

100.47303885384376

### El generador np.random.poisson()
Devuelve un arreglo de números aleatorios que siguien la distribución de Poisson:
$$
f(k; \lambda) = \frac{\lambda^k e^{-k}}{k!},
$$
El paŕametro de entrada es el número de eventos $k$ esperado en un intervalo $\lambda$.

In [209]:
np.random.poisson(9, size=5)

array([10,  6, 11,  8, 12])

### El generador np.random.uniform()
Devuelve un arreglo de números aleatorios que siguien la distribución uniforme:
$$
p(x) = \frac{1}{b-a}
$$
Opera sobre el intervalo $[a, b)$. Los parámetros de entrada son el límite inferior, el límite superior y el tamaño del arreglo.

In [210]:
np.random.uniform(1, 10, 10)

array([6.67855066, 4.35666365, 7.87532284, 7.51761464, 2.78213819,
       8.45075089, 4.80187025, 1.56042782, 1.3747928 , 1.58719405])

## Leyendo y creando archivos de texto
Guardar un arreglo de numpy como un archivo de texto

In [213]:
np.savetxt('Datos.txt', data3)

Es posible leer un archivo de texto y convertirlo a un arreglo de numpy

In [216]:
a = np.genfromtxt('Datos.txt')
a

array([[1., 2.],
       [3., 5.],
       [4., 6.]])